### PR TITLE
refactor: less #[inline(always)]

### PR DESCRIPTION
**Pull request by FreezyLemon**
It's a bit unnecessary to have inline(always) on getter functions IMHO. The `polyX` functions are also very small, so a normal inline attribute is enough.

### CODE REVIEW

**Comment by shssoichiro** [comment]
Could you change the ones you removed to be normal `#[inline]` instead? I think the original intent of these was to allow them to be inlined across crates, since they're so small and Rust does not do that automatically unless you have LTO. I can't remember the reasoning for setting them to `#[inline(always)]`, but it does indeed seem unnecessary.

**Comment by FreezyLemon** [comment]
Sure. I didn't actually know Rust inlined across crates at all without LTO, it's good to know that #[inline] enables that

**Review by shssoichiro — APPROVED** [review]
Thanks!

**Comment by FreezyLemon** [comment]
> I think the original intent of these was to allow them to be inlined across crates, since they're so small and Rust does not do that by default unless you enable LTO.

I stumbled over something just now and remembered this PR: This [has been changed](https://github.com/rust-lang/rust/pull/116505) for 1.75, and is now done automatically for small enough functions. Not saying this should be changed here, but just FYI.

**Comment by shssoichiro** [comment]
Huh, I had forgotten about that change. Probably worth keeping this for now for users on older Rust versions, since it doesn't hurt to keep around.

I also remembered that the reason I put `inline(always)` on the `poly` functions is because I really did want them inlined always, but as you mentioned, a normal `#[inline]` is probably enough to hint that they should be inlined. It almost feels like it would be a compiler bug if it didn't.

**Comment by FreezyLemon** [comment]
> I also remembered that the reason I put inline(always) on the poly functions is because I really did want them inlined always

Yeah that's fair enough, inlining is critical for those. Maybe that should've been left as-is actually.

>  It almost feels like it would be a compiler bug if it didn't.

Also true. But it might've been better still to just force it. IDK

**Pull request merged**
