### PR TITLE
Remove two dependencies

### PR DESCRIPTION
**Pull request by FreezyLemon**
Remove `thiserror` and `paste`. Both are proc-macros, but `syn` is still required because of av-data using `num-derive` in a few places.

Still, I think these are simple changes (without API breakage) and fewer dependencies are good.

### CODE REVIEW

**Comment by shssoichiro** [comment]
I have mixed feelings about this, because of the increased boilerplate. Let me think about it... or convince me. 🤷‍♂️

**Comment by FreezyLemon** [comment]
You mean because the `#[error("...")]` syntax is nicer than the manual Error implementation? I can see that.. I've made it a habit to avoid proc-macros unless they pull their weight. Maybe it was overzealous in this case, because we can't avoid `syn` anyways with `av-data` still pulling it in. And I've gotten used to the boilerplate, I guess.

I don't really have a strong stance on this. If you think it's not worth it, that's fine.

**Comment by shssoichiro** [comment]
That as well as the duplication from removing `paste`. What impact does it have on the compilation time? Maybe not as much as we'd prefer since we still need syn at the moment.

**Comment by FreezyLemon** [comment]
A fresh build on my notebook is a tiny bit quicker (0.5s / 10%)...

I tried replacing `num-derive` (last syn-based dependency) in [av-data](https://github.com/rust-av/rust-av/pull/193) a few months ago, but that was understandably rejected. The [relevant commit](https://github.com/rust-av/rust-av/commit/cad54be819c6f9f2fa8e614e311c45854201f533) is still accessible, but as you can see, the code for that is an arguable downgrade. I guess we may need to wait for something like https://github.com/rust-lang/rfcs/pull/3698

**Comment by shssoichiro** [comment]
We may be waiting a long time for that. In the meantime, I suppose this change isn't that bad, since it's just a small amount of boilerplate.

**Pull request merged**
